### ISSUE TITLE
Support ECS and Lambda running in multiple accounts

### ISSUE THREAD

**Issue by ikorihn** [fujiwara/ecrm#36]
Thank you for providing such an excellent tool!

We are operating with ECS and Lambda running in multiple AWS accounts. Specifically, we have centralized our ECR in one account, while ECS in various accounts pull images from this single ECR.

Currently, it seems that this tool assumes ECS and ECR are operating within the same account. I would like to request the ability to scan ECS across multiple accounts and exclude the images in use from being flagged for deletion.

I would greatly appreciate it if you could consider this feature.

**Comment by fujiwara** [comment]
@ikorihn Thank you for the request!

I'm working on #44, this PR enables to support multi region/accounts. Is it satisfy your needs?

**Comment by ikorihn** [comment]
@fujiwara 
I'm terribly sorry for the delayed response.
Thank you very much for merging the pull request!
It looks fine 🎉
