### ISSUE TITLE
Typo in ecrm.yaml file: "aliase" should be "alias"

### ISSUE THREAD

**Issue by y16ra** [fujiwara/ecrm#54]
There is a typo in the ecrm.yaml file. 
The key keep_aliase should be corrected to keep_alias.

Expected Result: The key should be keep_alias: true.  

Actual Result: The key is currently keep_aliase: true. 

Suggested Fix: Change keep_aliase to keep_alias in the ecrm.yaml file. 

Thank you!

**Comment by fujiwara** [comment]
@y16ra Hi. I've fixed this typo by #58. Thank you!
